/**
 * defaultProfiles holds our seed data for the profiles page
 * @param {Object} profile - The complete Profile Object
 * @param {string} id - The unique identifier for the Profile
 * @param {string} userId - The unique identifier that connects the Profile to a User (1 per user)
 * @param {string} name - The name of the Profile
 * @param {string} image - The rounded profile picture associated with the Profile
 * @param {string} summary - The status that a Profile can set (meant to be a short statement)
 * @param {string} description - The description telling what the Profile (person) is about or looking for
 * @param {string} groupname - The group that a Profile has joined (self-reported)
 * @param {string} descimage - The square image that can be more descriptive associated with the Profile
 */

export const defaultProfiles = [
  {
    id: 'hy-1',
    userId: '1',
    name: 'Hanako Yamada',
    image: '/pfps/hy1.jpg',
    summary: 'casual hiker looking for friends',
    description: 'I am excited to go on hikes with all types of people. I just moved here recently, so I am looking to make friends and do less intensive hikes.',
    groupname: 'HNL Hiking Club',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'kb-1',
    userId: '2',
    name: 'Kim Berley',
    image: '/pfps/kb1.jpg',
    summary: 'more computer science or math nerds welcome',
    description: 'I just like talking about math with people.',
    groupname: 'Mathemagical Hikes',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'rd-1',
    userId: '3',
    name: 'Renata Daugherty',
    image: '/pfps/rd1.jpg',
    summary: 'Just moved here!',
    description: 'I am excited to be studying marine biology. I love hiking back home and have heard that there are many beautiful ones here.',
    groupname: 'Brunch Club with the Girls',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'vt-1',
    userId: '4',
    name: 'Virginia Thompson',
    image: '/pfps/vt1.png',
    summary: 'I am a UH Foreign Exchange Student from France',
    description: 'Excited to meet new people from all around the world. I love all kinds of beaches.',
    groupname: 'International Student Association',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'pf-1',
    userId: '5',
    name: 'Payton Frye',
    image: '/pfps/pf1.jpg',
    summary: 'Love cabin life!',
    description: 'I love to go camping and am excited to learn about the best spots! I want to make new friends! It is very nice to meet you all.',
    groupname: 'Camping and Hiking',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'od-1',
    userId: '6',
    name: 'Olive Davila',
    image: '/pfps/od1.jpg',
    summary: 'I love icecream!',
    description: 'Just excited to meet new people.',
    groupname: 'Anime and Manga Society of Hawaii',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'lo-1',
    userId: '7',
    name: 'Lyanna Ochoa',
    image: '/pfps/lo1.jpg',
    summary: 'I love icecream pizzas deepfried!',
    description: 'Just excited to meet new people.',
    groupname: 'Boba Time',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'ke-1',
    userId: '8',
    name: 'Kayla Erickson',
    image: '/pfps/ke1.jpg',
    summary: 'I love learning about new cultures',
    description: 'Just moved here studying more about geography. Currently am taking a class learning about the history of tea which I think is pretty cool. I prefer just having fun and good vibes. Also please any reccomendations for brunch places?',
    groupname: 'Brunch Club with the Girls',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'hh-1',
    userId: '9',
    name: 'Holly Haley',
    image: '/pfps/hh1.jpg',
    summary: 'Go Ducks!!!',
    description: 'Have a lot of experience doing hikes? Consider joining our group The Ducks. Seriously though, I have always loved hiking and our family does a big hike every year back in Washington where I am from.',
    groupname: 'Ducks',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'gm-1',
    userId: '10',
    name: 'Genevieve Morales',
    image: '/pfps/gm1.jpg',
    summary: 'Yes I like Spiderman',
    description: 'Spiderman is great. Everyone likes talking about Spiderman! But yeah I would love to meet new people and if you could stand a rant or two about how great Spiderman is we will get along swimmingly.',
    groupname: 'Spider Man for President',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'ah-2',
    userId: '11',
    name: 'Amy Holloway',
    image: '/pfps/ah2.jpg',
    summary: 'Yes my pfp is a vibe',
    description: 'Love the great outdoors and an even greater brunch afterward with some mimosas.',
    groupname: 'Brunch Club with the Girls',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'gr-1',
    userId: '12',
    name: 'Gemma Richards',
    image: '/pfps/gr1.jpg',
    summary: 'Would love to take pictures of the great outdoors with some great buds',
    description: 'Would love to go on more hikes and meet more new poeple.',
    groupname: 'Bird Watchers',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'sp-1',
    userId: '13',
    name: 'Serena Powers',
    image: '/pfps/sp1.jpg',
    summary: 'Just looking to make new friends',
    description: 'I could really go for a pizza bagel right about now. But seriously I would like to meet some new people, especially as I am an foreign exchange student.',
    groupname: 'International Student Association',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'mr-1',
    userId: '14',
    name: 'Marilyn Rollins',
    image: '/pfps/mr1.jpg',
    summary: 'I am in the theatre department',
    description: 'Nature always influences art right. That is why I am here: to meet new people and get inspired by nature.',
    groupname: 'Naturespirators',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'td-1',
    userId: '15',
    name: 'Taylor Diaz',
    image: '/pfps/td1.jpg',
    summary: 'I always love doing hikeds',
    description: 'I am more of a serious hiker. I have heard that Hawaii has a lot to offer.',
    groupname: 'Butterfly to New Heights',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'rc-1',
    userId: '16',
    name: 'Raya Cardenas',
    image: '/pfps/rc1.jpg',
    summary: 'I just got dumped.',
    description: 'I needed to get over them yesterday.',
    groupname: 'Running Club - Manoa Chapter',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'la-1',
    userId: '17',
    name: 'Louise Ayers',
    image: '/pfps/la1.jpg',
    summary: 'I just got married.',
    description: 'I would like to know all of the good spots in Hawaii before I come here for my honeymoon this Christmas!',
    groupname: 'N/A',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'bh-1',
    userId: '18',
    name: 'Blaire Hart',
    image: '/pfps/bh1.jpg',
    summary: 'I could use a break now or yesterday please',
    description: 'I have been very busy in my office job with no time for much else. I mean this picture was taken like 3 years ago! I feel like I have been doing nothing but typing. Would love to have some human social interaction.',
    groupname: 'Muffin Time',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'ey-1',
    userId: '19',
    name: 'Emmaline Yoder',
    image: '/pfps/ey1.jpg',
    summary: 'Today is the present',
    description: 'Just moved here and would like to meet some new people. Am currently studying Russian History; would love to learn about other cultures. Also anyone know which are the best food spots here?',
    groupname: 'N/A',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'kc-1',
    userId: '20',
    name: 'Kali Castillo',
    image: '/pfps/kc1.jpg',
    summary: 'Rootbeer is the best soda. sue me.',
    description: 'I could go for a rootbeer float and some pizza right now.',
    groupname: 'Local Grindz',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'jd-1',
    userId: '21',
    name: 'John Doe',
    image: '/pfps/jd1.jpg',
    summary: 'looking to add to our group Ducks',
    description: 'I have been hiking for a while on quite intensive hikes. I prefer going with a smaller group, however we are still available to accept a couple more members. Please only consider if you have a decent amount of experience. We go on some pretty intensive hikes.',
    groupname: 'Ducks',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'br-1',
    userId: '22',
    name: 'Bradley Raymond',
    image: '/pfps/br1.jpg',
    summary: 'my favorite food is ramen',
    description: 'I like the ocean and chill vibes',
    groupname: 'Association for Computing Machinery',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'gh-1',
    userId: '23',
    name: 'Giovanni Hammond',
    image: '/pfps/gh1.jpg',
    summary: 'Love to take professional photographs of the outdoors',
    description: 'I love taking photos of the outdoors and my friends! Looking to meet new people.',
    groupname: 'Butterfly to New Heights',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'bc-1',
    userId: '24',
    name: 'Barrett Case',
    image: '/pfps/bc1.jpg',
    summary: 'Just excited to meet new people',
    description: 'Moved here last year and finally graduated yay! Now that I have more time, I would like to explore more of the outdoors activities here.',
    groupname: 'Theatre Club',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'es-1',
    userId: '25',
    name: 'Elliot Sullivan',
    image: '/pfps/es1.jpg',
    summary: 'Retired man wanting to look at the birds',
    description: 'Just wanted to share with others if interested in learning more about all of the different endemic birds that live here. ',
    groupname: 'Bird Watchers',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'lk-1',
    userId: '26',
    name: 'Lucas Kane',
    image: '/pfps/lk1.jpg',
    summary: 'Love checking out new parks',
    description: 'I love looking at the beautiful scenery in parks. Just would like to make some friends, and I like chess!',
    groupname: 'Running Club - Manoa Chapter',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'ah-3',
    userId: '27',
    name: 'Adam Hunt',
    image: '/pfps/ah3.jpg',
    summary: 'Like running and chill vibes',
    description: 'I like running back home in Arizona, and I just moved here and would like to meet some new people. Lemme know if you are interested in the best ever butternut squash soup recipe btw.',
    groupname: 'Muffin Time',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'sb-1',
    userId: '28',
    name: 'Sergio Bishop',
    image: '/pfps/sb1.jpg',
    summary: 'Getting back into guitar and tuning into nature (pun intended)',
    description: 'I am just a beginner but if anyone would like to get together in a band sometime that would be nice. I just want to try and connect more iwth nature; nature always finds a way to inspire.',
    groupname: 'Jazz - The Rocks Band',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'ad-1',
    userId: '29',
    name: 'Alden Dunn',
    image: '/pfps/ad1.jpg',
    summary: 'Favorite Food is watermelon on a hot summer day',
    description: 'I have quite a bit of experience doing hikes here. Mostly just here for our group the Ducks. Please consider applying if you have a lot of experience. Love the more intensive hikes with a great crew!',
    groupname: 'Ducks',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'ab-1',
    userId: '30',
    name: 'Anthony Ballard',
    image: '/pfps/ab1.jpg',
    summary: 'Love taking pictures of wildlife',
    description: 'Just moved here and am studying marine biology at UH. I am very excited to take lots of pictures of all of the cool animals here. Did you know that like 90 percent of animals here are endemic? something like that. Also the weather here is super nice.',
    groupname: 'Gamers Yo',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'tr-1',
    userId: '31',
    name: 'Tony Rowe',
    image: '/pfps/tr1.jpg',
    summary: 'Need coffee yesterday',
    description: 'Need to meet new people that are not from work.',
    groupname: 'Naturespirators',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'lc-1',
    userId: '32',
    name: 'Lennon Carpenter',
    image: '/pfps/lc1.jpg',
    summary: 'My favorite food is pizza bagels',
    description: 'I am a foreign exchange student from Britain. Just heard about this through a friend and would like to meet more people.',
    groupname: 'International Student Association',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'mg-1',
    userId: '33',
    name: 'Mack Griffin',
    image: '/pfps/mg1.jpg',
    summary: 'I love hearing the soothing waves',
    description: 'Are the waves not the most soothing thing out there?',
    groupname: 'Mathemagical Hikes',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'jb-1',
    userId: '34',
    name: 'Johnathan Bruce',
    image: '/pfps/jb1.jpg',
    summary: 'Playing tunes wherever I go',
    description: 'Wanted to meet and get to know more people. Let me know if you are up for a jam session.',
    groupname: 'Jazz - The Rocks Band',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'lg-1',
    userId: '35',
    name: 'Landry Garcia',
    image: '/pfps/lg1.jpg',
    summary: 'Interested in art',
    description: 'I love talking about all different kinds of art. I love learning more about different history from all around the world.',
    groupname: 'Naturespirators',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'bg-1',
    userId: '36',
    name: 'Briar Gordon',
    image: '/pfps/bg1.jpg',
    summary: 'I could really go for an icecream sandwich right about now.',
    description: 'Economics and Business but I was asked by my friends to get out more so this is proof of that I suppose.',
    groupname: 'Gamers Yo',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'lw-1',
    userId: '37',
    name: 'Lennon Wagner',
    image: '/pfps/lw1.jpg',
    summary: 'Sunsets and Sunrises are proof that you will be ok',
    description: 'I just like talking with new people',
    groupname: 'Local Grindz',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'db-1',
    userId: '38',
    name: 'Daniel Beard',
    image: '/pfps/db1.jpg',
    summary: 'Football is life man',
    description: 'Football or as you call it Soccer wooooooo. Yeah but I think getting more into nature would be nice for me too.',
    groupname: 'Local Grindz',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'rm-1',
    userId: '39',
    name: 'Rowan Mayo',
    image: '/pfps/rm1.jpg',
    summary: 'I will stare atchu forever',
    description: 'I will stare at you forever. It is the deal with being a theatre kid',
    groupname: 'Boba Time',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'jf-1',
    userId: '40',
    name: 'Jose Felix',
    image: '/pfps/jf1.jpg',
    summary: 'I could really go for a glass of water right about now',
    description: 'A cool photo that I took. Cannot wait to meet more people.',
    groupname: 'N/A',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'ts-1',
    userId: '41',
    name: 'The Steins',
    image: '/pfps/ts1.jpg',
    summary: 'We love meeting new people',
    description: 'We are Jill and Jack Stein. We love going on hikes together but we would love to meet new people! Just moved here a little while ago.',
    groupname: 'N/A',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'ti-1',
    userId: '42',
    name: 'The Ibarras',
    image: '/pfps/ti1.jpg',
    summary: 'We love meeting new people',
    description: 'We are Jon and Jill Ibara. We would love to share more about our culture with others.',
    groupname: 'N/A',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'cats-1',
    userId: '43',
    name: 'Miss Diffident of Wales',
    image: '/pfps/cats1.jpg',
    summary: 'Churu only. Otherwise talk to the paw',
    description: 'Meow Meow meow meow Meow meow.',
    groupname: 'N/A',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'cats-2',
    userId: '44',
    name: 'Mungojerrie',
    image: '/pfps/cats2.jpg',
    summary: 'Do not talk to me on Meowndays',
    description: 'Meow Meow meow meow Meow meow.',
    groupname: 'N/A',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'cats-3',
    userId: '45',
    name: 'Mc Bonkers',
    image: '/pfps/cats3.jpg',
    summary: 'Yes bonkers. It is a very important career that generations of my family have had.',
    description: 'Meow Meow meow meow Meow meow.',
    groupname: 'N/A',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'cats-4',
    userId: '46',
    name: 'Daisy-Mae',
    image: '/pfps/cats4.jpg',
    summary: 'Daisies are my favorite flowers.',
    description: 'Meow Meow meow meow Meow meow.',
    groupname: 'N/A',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'cats-5',
    userId: '47',
    name: 'Mrs Impatient',
    image: '/pfps/cats5.jpg',
    summary: 'No',
    description: 'Meow Meow meow meow Meow meow.',
    groupname: 'N/A',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'cats-6',
    userId: '48',
    name: 'Mr Fastidiouspants',
    image: '/pfps/cats6.jpg',
    summary: 'Eh, the name suits me.',
    description: 'Meow Meow meow meow Meow meow.',
    groupname: 'N/A',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'cats-7',
    userId: '49',
    name: 'Chess',
    image: '/pfps/cats7.jpg',
    summary: 'I am a 3 time professional world winning chess cat. The first world winning chess cat.',
    description: 'Meow Meow meow meow Meow meow.',
    groupname: 'N/A',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
  {
    id: 'cats-8',
    userId: '50',
    name: 'Flowers',
    image: '/pfps/cats8.jpg',
    summary: 'Yay flowers!',
    description: 'Meow Meow meow meow Meow meow.',
    groupname: 'N/A',
    descimage: '/images/pizza-bagels-descimage.jpg',
  },
];

export default defaultProfiles;
