/**
 * defaultGroups holds our seed data for the groups page
 * @param {Object} group - The complete Group Object
 * @param {string} id - The unique identifier for the Group
 * @param {string} userId - The unique identifier that connects the Group to a User (as many as like)
 * @param {string} name - The name of the Group
 * @param {string} image - The rounded profile image associated with the Group
 * @param {number} members - The number of people that are currently in the Group
 * @param {number} maxmembers - The maximum number of people that the Group would like to have
 * @param {string} description - The description telling what the Group is about
 * @param {Date} lastdate - The last date that the group has had a meeting
 * @param {string} lastlocation - The last location that the Group has been to during their last meeting
 */

import { Commitment } from "@prisma/client";

export const defaultGroups = [
  {
    id: 'math-hikes-default',
    userId: '1',
    name: 'Mathemagical Hikes',
    image: '/groups/mathclub.jpeg',
    members: 10,
    maxmembers: null,
    intensity: Commitment.Casual,
    description: 'We go on hikes and talk about math. Please join if interested, we always welcome new members. Hikes typically range from relatively easy to moderate.',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Manoa Falls',
  },
  {
    id: 'ducks-default',
    userId: '2',
    name: 'Ducks',
    image: '/groups/ducks.jpg',
    members: 3,
    maxmembers: 5,
    intensity: Commitment.Serious,
    description: 'Looking to add a couple more members to our small group. We tend to go on more difficult hikes, so please only consider if you have more experience.',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Koko Head',
  },
  {
    id: 'hnl-hiking-default',
    userId: '3',
    name: 'HNL Hiking Club',
    image: '/groups/hnlhike.jpeg',
    members: 55,
    maxmembers: null,
    intensity: Commitment.Moderate,
    description: 'We heard about this website and wanted to branch out. Our group number is bigger than what is listed but we have only included members that have profiles here. Always welcome more and every hike is a big crowd.',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Diamond Head',
  },
  {
    id: 'brunch-girls-default',
    userId: '4',
    name: 'Brunch Club with the Girls',
    image: '/groups/brunch.jpg',
    members: 25,
    maxmembers: null,
    intensity: Commitment.Sometimes_Casual,
    description: 'We love brunch. Seriously we know all the best spots. Please come and join everyone is welcome',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Makapuʻu Lighthouse Trail',
  },
  {
    id: 'camp-default',
    userId: '5',
    name: 'Camping and Hiking',
    image: '/groups/camp.jpg',
    members: 7,
    maxmembers: null,
    intensity: Commitment.Serious,
    description: 'We love finding the best spots to go camping. We also do hikes occasionally, especially during the very busy weeks before finals ;-;',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Wiliwilinui Ridge Trail',
  },
  {
    id: 'ams-default',
    userId: '6',
    name: 'Anime and Manga Society of Hawaii',
    image: '/groups/ams.jpg',
    members: 73,
    maxmembers: null,
    intensity: Commitment.Casual,
    description: 'Talking about anime and manga while looking at beautiful nature. We occasionally have watch parties and things too.',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Manoa Falls',
  },
  {
    id: 'boba-default',
    userId: '7',
    name: 'Boba Time',
    image: '/groups/boba.jpg',
    members: 9,
    maxmembers: 15,
    intensity: Commitment.Moderate,
    description: 'We focus on talking about feelings with each other. Sometimes having a hard week and sharing it with others makes it less hard. Exercise can also help make you feel better. We are not sure if we fully believe that but we do believe if you do it with others, then you will feel better for sure. (Looking for new members currently as some people have graudated recently.)',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Manoa Falls',
  },
  {
    id: 'baking-default',
    userId: '8',
    name: 'Muffin Time',
    image: '/groups/baking.jpg',
    members: 34,
    maxmembers: 40,
    intensity: Commitment.Moderate,
    description: 'We love baking! Bring your best recipes for protein/granola bars. Please only consider joining if you enjoy moderately difficult hikes though.',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Waimano Falls Trail',
  },
  {
    id: 'poke-default',
    userId: '9',
    name: 'Local Grindz',
    image: '/groups/poke.jpg',
    members: 3,
    maxmembers: null,
    intensity: Commitment.Casual,
    description: 'Just joined recently. Excited to meet new people and eat new delicious foods. Please join and let us know any reccomendations you have.',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Manoa Falls',
  },
  {
    id: 'bird-watchers-default',
    userId: '10',
    name: 'Bird Watchers',
    image: '/groups/birdwatchers.jpg',
    members: 78,
    maxmembers: 100,
    intensity: Commitment.Sometimes_Moderate,
    description: 'Love Bird Watching? Consider joining our group. We love talking about the many different types of birds, migration patterns, anything you can think of. We also try to give tea to drink!',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Olomana Three Peaks Trail',
  },
  {
    id: 'game-default',
    userId: '11',
    name: 'Gamers Yo',
    image: '/groups/game.jpg',
    members: 23,
    maxmembers: null,
    intensity: Commitment.Casual,
    description: 'After hiking, we play video games. Mostly Super Smash Bros and Mario Kart, although we are open to more suggestions.',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Manoa Falls',
  },
  {
    id: 'isa-default',
    userId: '12',
    name: 'International Student Association',
    image: '/groups/isa.jpg',
    members: 57,
    maxmembers: null,
    intensity: Commitment.Moderate,
    description: 'Meet other International Exchange Students through Hiking. We also have picnics after the hike is over. Everyone is welcome',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Makapuʻu Lighthouse Trail',
  },
  {
    id: 'running-default',
    userId: '13',
    name: 'Running Club - Manoa Chapter',
    image: '/groups/running.jpg',
    members: 63,
    maxmembers: null,
    intensity: Commitment.Serious,
    description: 'We love going on runs and wanted to expand trying hikes as well. Please only consider joining if you have quite a bit of experience with hiking.',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Kaʻena Point Trail',
  },
  {
    id: 'acm-default',
    userId: '14',
    name: 'Association for Computing Machinery',
    image: '/groups/acm.png',
    members: 65,
    maxmembers: null,
    intensity: Commitment.Casual,
    description: 'We heard about this project and wanted to put a group in. We love talking about anything related. If you have any questions regarding the computer science department and what we do here, please let us know.',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Manoa Falls',
  },
  {
    id: 'instrument-default',
    userId: '15',
    name: 'Jazz - The Rocks Band',
    image: '/groups/instrument.jpg',
    members: 7,
    maxmembers: 10,
    intensity: Commitment.Sometimes_Casual,
    description: 'We like playing together in band. Please message us and we will let you know if you would be a good fit.',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Aiea Loop Trail',
  },
  {
    id: 'art-default',
    userId: '16',
    name: 'Naturespirators',
    image: '/groups/art.jpg',
    members: 18,
    maxmembers: null,
    intensity: Commitment.Moderate,
    description: 'We like going on hikes and then drawing sketches afterwards. Bring all of your watercolors!',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Kaʻena Point Trail',
  },
  {
    id: 'spiderman-default',
    userId: '17',
    name: 'Spider Man for President',
    image: '/groups/spiderman.jpg',
    members: 2,
    maxmembers: null,
    intensity: Commitment.Serious,
    description: 'Give it your all for Spiderman to become president! If you are not 10,000% committed to the cause get out, respectfully.',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Kaʻena Point Trail',
  },
  {
    id: 'theatre-default',
    userId: '18',
    name: 'Theatre Club',
    image: '/groups/theatre.jpg',
    members: 25,
    maxmembers: null,
    intensity: Commitment.Casual,
    description: 'Are you part of a production and would like to get to know your crewmembers and castmates better? Join us every Saturday for a hike! We are very casual so no worries.',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Makapuʻu Lighthouse Trail',
  },
  {
    id: 'pizza-default',
    userId: '19',
    name: 'Pizza Club',
    image: '/groups/pizza.jpg',
    members: 68,
    maxmembers: null,
    intensity: Commitment.Casual,
    description: 'We like all kinds of pizza. Yes, this includes pineapple and anchovy. Every week we talk about every different kind of pizza and try to rank them while on a hike. Then we go to this awesome pizza place. Everyone welcome!',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Makapuʻu Lighthouse Trail',
  },
  {
    id: 'butterfly-default',
    userId: '20',
    name: 'Butterfly to New Heights',
    image: '/groups/butterfly.jpg',
    members: 2,
    maxmembers: 10,
    intensity: Commitment.Serious,
    description: 'Only considering people who have lots of experience. We only do the hardest hikes possible.',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Olomana Three Peaks Trail',
  },
];

export default defaultGroups;
